name: "iOS debug build workflow"
on:
  push:
    tags:
    - '*'
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  test:
    name: "Testing pre-release"
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze

  pre-release:
    if: github.event_name != 'pull_request'
    name: "Build and deploy pre-release"
    runs-on: macOS-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.0'
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter pub get
      - run: mkdir -p Payload
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - run: ls build/ios/iphoneos/
      - run: tree build/ios/iphoneos/
      - run: cp build/ios/iphoneos/Runner.app/ Payload/Runner.app/
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r -y Payload.zip Payload/Runner.app
      - run: mv Payload.zip Payload.ipa
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest dev build for iOS"
          files: |
            build/ios/iphoneos/Runner.app/*
            Payload.zip